name: auto-release

on:
  push:
    branches:
      - main
      - master
      - production

jobs:
  auto:
    uses: itisopen/.github/.github/workflows/shared-auto-release.yml@main
    with:
      publish: true
    secrets: inherit
